# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: false
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/arbac_verifier/all/arbac_verifier.rbi
#
# arbac_verifier-1.0.6

module ARBACVerifier
end
class ARBACVerifier::ReachabilityVerifier
  def initialize(*args, **, &blk); end
  def instance(*args, **, &blk); end
  def verify(*args, **, &blk); end
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
