on:
  push:
    branches: [ "development" ]

jobs:
  type-check:
    name: Sorbet Type Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.1

      - name: Install dependencies
        run: bundle install

      - name: Run Sorbet
        run: bundle exec srb tc

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: type-check

    strategy:
      matrix:
        ruby-version: [3.1]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: bundle exec rspec

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}